import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    root:{
        flex:1,
        justifyContent:'center',
        padding:20,
        gap:10
    },
    text:{
        fontSize:20,
        fontWeight:'bold',
        textAlign:'center',
        color:'white'
    },
    message:{
        
        width:428
    },
    textRedirect:{
        marginTop:20,
        textAlign:'center',
        fontSize:15,
        fontWeight:'bold',
        color:'#705aa9'
    },
    rootActivity:{
        flex:1,
        justifyContent:'center',
        alignContent:'center'
    },
    rootHome:{
        flex:1,
        marginHorizontal:25,
        marginVertical:50
    },
    header:{
        flexDirection:'row',
        gap:15,
        alignItems:'center'
    },
    iconHeader:{
        alignItems:"flex-end",
        flex:1
    },
    modal:{
        padding:20,
        marginHorizontal:20,
        backgroundColor:'#fff',
        borderRadius:10,
        gap:10
    },
    rootListProduct:{
        marginTop:10,
        flexDirection:'row',
        padding:10,
        alignItems:'center',
        gap:20
    },
    facProduct:{
        position:'absolute',
        bottom:20,
        right:15
    },
    rootInputsProduct:{
        flexDirection:'row'
        , gap:35
    },
    rootDetail:{
        flex:1,
        marginTop:30,
        paddingHorizontal:20,
        backgroundColor:'#fff',
        gap:20
    },
    textDetail:{
        fontWeight:'bold',
        fontSize:16
    },
    iconSignOut:{
        marginTop:20,
        alignItems:'center'
    }
})

